services:
  - type: web
    name: sms-spam-detection-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TRANSFORMERS_CACHE
        value: /app/cache
      - key: TORCH_HOME
        value: /app/cache 