services:
  - type: web
    name: capstone-model
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TRANSFORMERS_CACHE
        value: /app/cache
      - key: TORCH_HOME
        value: /app/cache 